run:
  timeout: 5m
  build-tags:
    - with_yara
    - with_ebpf

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - unconvert
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - staticcheck
